

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    hideakitai/MQTTPubSubClient
    links2004/WebSockets
    rweather/Crypto

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DPICOWEBSOCKET_DEBUG
    -I../config

board_build.embed_files = data/cert/x509_crt_bundle.bin